//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        public Fixture()
        {
            this.FixtureEvents = new HashSet<FixtureEvent>();
        }
    
        public int ID { get; set; }
        public string MatchID { get; set; }
        public int LeaugeID { get; set; }
        public string Host { get; set; }
        public string Guest { get; set; }
        public string Unix_KickOff { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Local_KickOff { get; set; }
        public Nullable<System.DateTime> Pre_Local_KickOff { get; set; }
        public int IsPreKickOffSent { get; set; }
        public int IsMatchSummSent { get; set; }
        public int IsDailySummSent { get; set; }
        public string Score { get; set; }
        public Nullable<bool> IsScoreAET { get; set; }
        public Nullable<System.DateTime> Local_Finish { get; set; }
    
        public virtual League League { get; set; }
        public virtual ICollection<FixtureEvent> FixtureEvents { get; set; }
    }
}
