//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;




// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace GoalAlert
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://beybegi.ru/xmlschema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("livescore-feed-document", Namespace = "http://beybegi.ru/xmlschema.xsd", IsNullable = false)]
    public partial class livescorefeeddocument
    {

        private livescorefeeddocumentMatcheslist[] matcheslistField;

        private string timestamp_createdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("matches-list")]
        public livescorefeeddocumentMatcheslist[] matcheslist
        {
            get
            {
                return this.matcheslistField;
            }
            set
            {
                this.matcheslistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string timestamp_created
        {
            get
            {
                return this.timestamp_createdField;
            }
            set
            {
                this.timestamp_createdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://beybegi.ru/xmlschema.xsd")]
    public partial class livescorefeeddocumentMatcheslist
    {

        private livescorefeeddocumentMatcheslistMatch[] matchField;

        private string totalcountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("match")]
        public livescorefeeddocumentMatcheslistMatch[] match
        {
            get
            {
                return this.matchField;
            }
            set
            {
                this.matchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("total-count")]
        public string totalcount
        {
            get
            {
                return this.totalcountField;
            }
            set
            {
                this.totalcountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://beybegi.ru/xmlschema.xsd")]
    public partial class livescorefeeddocumentMatcheslistMatch
    {

        private string scoreField;

        private livescorefeeddocumentMatcheslistMatchContest[] contestField;

        private livescorefeeddocumentMatcheslistMatchTeams[] teamsField;

        private livescorefeeddocumentMatcheslistMatchMatcheventsEvent[][] matcheventsField;

        private string idField;

        private string timestampstartsField;

        private string statusField;

        /// <remarks/>
        public string score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contest", IsNullable = true)]
        public livescorefeeddocumentMatcheslistMatchContest[] contest
        {
            get
            {
                return this.contestField;
            }
            set
            {
                this.contestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("teams")]
        public livescorefeeddocumentMatcheslistMatchTeams[] teams
        {
            get
            {
                return this.teamsField;
            }
            set
            {
                this.teamsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("match-events")]
        [System.Xml.Serialization.XmlArrayItemAttribute("event", typeof(livescorefeeddocumentMatcheslistMatchMatcheventsEvent), IsNullable = false)]
        public livescorefeeddocumentMatcheslistMatchMatcheventsEvent[][] matchevents
        {
            get
            {
                return this.matcheventsField;
            }
            set
            {
                this.matcheventsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("timestamp-starts")]
        public string timestampstarts
        {
            get
            {
                return this.timestampstartsField;
            }
            set
            {
                this.timestampstartsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://beybegi.ru/xmlschema.xsd")]
    public partial class livescorefeeddocumentMatcheslistMatchContest
    {

        private string valueField;

        private string valueField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField1;
            }
            set
            {
                this.valueField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://beybegi.ru/xmlschema.xsd")]
    public partial class livescorefeeddocumentMatcheslistMatchTeams
    {

        private string hostsField;

        private string guestsField;

        /// <remarks/>
        public string hosts
        {
            get
            {
                return this.hostsField;
            }
            set
            {
                this.hostsField = value;
            }
        }

        /// <remarks/>
        public string guests
        {
            get
            {
                return this.guestsField;
            }
            set
            {
                this.guestsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://beybegi.ru/xmlschema.xsd")]
    public partial class livescorefeeddocumentMatcheslistMatchMatcheventsEvent
    {

        private string playerField;

        private string minuteField;

        private string scoreField;

        private livescorefeeddocumentMatcheslistMatchMatcheventsEventTeam[] teamField;

        private string typeField;

        /// <remarks/>
        public string player
        {
            get
            {
                return this.playerField;
            }
            set
            {
                this.playerField = value;
            }
        }

        /// <remarks/>
        public string minute
        {
            get
            {
                return this.minuteField;
            }
            set
            {
                this.minuteField = value;
            }
        }

        /// <remarks/>
        public string score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("team", IsNullable = true)]
        public livescorefeeddocumentMatcheslistMatchMatcheventsEventTeam[] team
        {
            get
            {
                return this.teamField;
            }
            set
            {
                this.teamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://beybegi.ru/xmlschema.xsd")]
    public partial class livescorefeeddocumentMatcheslistMatchMatcheventsEventTeam
    {

        private string valueField;

        private string valueField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField1;
            }
            set
            {
                this.valueField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://beybegi.ru/xmlschema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://beybegi.ru/xmlschema.xsd", IsNullable = false)]
    public partial class NewDataSet
    {

        private livescorefeeddocument[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("livescore-feed-document")]
        public livescorefeeddocument[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}