//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beybegi.ru/xmlschema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("livescore-feed", Namespace="http://beybegi.ru/xmlschema.xsd", IsNullable=false)]
public partial class livescorefeed {
    
    private livescorefeedMatchesMatch[][] matchesField;
    
    private string timestamp_createdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("match", typeof(livescorefeedMatchesMatch), IsNullable=false)]
    public livescorefeedMatchesMatch[][] matches {
        get {
            return this.matchesField;
        }
        set {
            this.matchesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string timestamp_created {
        get {
            return this.timestamp_createdField;
        }
        set {
            this.timestamp_createdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beybegi.ru/xmlschema.xsd")]
public partial class livescorefeedMatchesMatch {
    
    private string scoreField;
    
    private livescorefeedMatchesMatchContest[] contestField;
    
    private livescorefeedMatchesMatchTeams[] teamsField;
    
    private livescorefeedMatchesMatchMatchdetails[] matchdetailsField;
    
    private livescorefeedMatchesMatchMatcheventsEvent[][] matcheventsField;
    
    private string idField;
    
    private string timestampstartsField;
    
    private string statusField;
    
    /// <remarks/>
    public string score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contest", IsNullable=true)]
    public livescorefeedMatchesMatchContest[] contest {
        get {
            return this.contestField;
        }
        set {
            this.contestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("teams")]
    public livescorefeedMatchesMatchTeams[] teams {
        get {
            return this.teamsField;
        }
        set {
            this.teamsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("match-details")]
    public livescorefeedMatchesMatchMatchdetails[] matchdetails {
        get {
            return this.matchdetailsField;
        }
        set {
            this.matchdetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("match-events")]
    [System.Xml.Serialization.XmlArrayItemAttribute("event", typeof(livescorefeedMatchesMatchMatcheventsEvent), IsNullable=false)]
    public livescorefeedMatchesMatchMatcheventsEvent[][] matchevents {
        get {
            return this.matcheventsField;
        }
        set {
            this.matcheventsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("timestamp-starts")]
    public string timestampstarts {
        get {
            return this.timestampstartsField;
        }
        set {
            this.timestampstartsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beybegi.ru/xmlschema.xsd")]
public partial class livescorefeedMatchesMatchContest {
    
    private string valueField;
    
    private string valueField1;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField1;
        }
        set {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beybegi.ru/xmlschema.xsd")]
public partial class livescorefeedMatchesMatchTeams {
    
    private string hostsField;
    
    private string guestsField;
    
    /// <remarks/>
    public string hosts {
        get {
            return this.hostsField;
        }
        set {
            this.hostsField = value;
        }
    }
    
    /// <remarks/>
    public string guests {
        get {
            return this.guestsField;
        }
        set {
            this.guestsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beybegi.ru/xmlschema.xsd")]
public partial class livescorefeedMatchesMatchMatchdetails {
    
    private string periodField;
    
    private string minuteField;
    
    /// <remarks/>
    public string period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    public string minute {
        get {
            return this.minuteField;
        }
        set {
            this.minuteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beybegi.ru/xmlschema.xsd")]
public partial class livescorefeedMatchesMatchMatcheventsEvent {
    
    private string playerField;
    
    private string minuteField;
    
    private string scoreField;
    
    private livescorefeedMatchesMatchMatcheventsEventTeam[] teamField;
    
    private string typeField;
    
    /// <remarks/>
    public string player {
        get {
            return this.playerField;
        }
        set {
            this.playerField = value;
        }
    }
    
    /// <remarks/>
    public string minute {
        get {
            return this.minuteField;
        }
        set {
            this.minuteField = value;
        }
    }
    
    /// <remarks/>
    public string score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("team", IsNullable=true)]
    public livescorefeedMatchesMatchMatcheventsEventTeam[] team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beybegi.ru/xmlschema.xsd")]
public partial class livescorefeedMatchesMatchMatcheventsEventTeam {
    
    private string valueField;
    
    private string valueField1;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField1;
        }
        set {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://beybegi.ru/xmlschema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://beybegi.ru/xmlschema.xsd", IsNullable=false)]
public partial class NewDataSet {
    
    private livescorefeed[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("livescore-feed")]
    public livescorefeed[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
