//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyDB
    {
        public int ID { get; set; }
        public string Keyword { get; set; }
        public string Code { get; set; }
        public string Details { get; set; }
        public bool Has_Sub { get; set; }
        public string SubCodeName { get; set; }
        public Nullable<int> OnceOff { get; set; }
        public int MonthToMonth { get; set; }
        public Nullable<int> DaysValid { get; set; }
        public string Freq { get; set; }
        public string OnPhoneDisplay { get; set; }
        public bool IsCreditBased { get; set; }
        public int CreditValue { get; set; }
        public string AlphaTag { get; set; }
        public bool IsDevActive { get; set; }
    }
}
