//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public League()
        {
            this.Fixtures = new HashSet<Fixture>();
        }
    
        public int LeagueID { get; set; }
        public string LeagueName { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsEnabled { get; set; }
    
        public virtual ICollection<Fixture> Fixtures { get; set; }
    }
}
