//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDB
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Cat { get; set; }
        public string MSISDN { get; set; }
        public string Shortcode { get; set; }
        public string Network { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<int> Freq { get; set; }
        public Nullable<System.DateTime> Sub { get; set; }
        public Nullable<System.DateTime> Exp { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
